#include <limits.h>
#include "include/core/platform.h"
#include "include/api/api.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/threaded/scheduler.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
int lf_reactor_c_main(int argc, const char* argv[]);
#include "include/core/federated/federate.h"
#include "include/core/federated/net_common.h"
#include "pythontarget.h"
// Code generated by the Lingua Franca compiler from:
// file://mnt/c/Users/jacky/Desktop/Federated_Learning/fed-gen/Main/src/Server.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/mnt/c/Users/jacky/Desktop/Federated_Learning/fed-gen/Main/src-gen/Server"
int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
const char* _lf_default_argv[] = { "dummy", "-k", "true" };
void _lf_set_default_command_line_options() {
        default_argc = 3;
        default_argv = _lf_default_argv;
}
#include "serverreactor1598031955.h"
#include "server1436171503_main.h"
#include "include/_Server_preamble.h"
// Array of pointers to timer triggers to be scheduled in _lf_initialize_timers().
trigger_t** _lf_timer_triggers = NULL;
int _lf_timer_triggers_size = 0;
// Array of pointers to startup triggers.
reaction_t* _lf_startup_reactions[1];
int _lf_startup_reactions_size = 1;
// Array of pointers to shutdown triggers.
reaction_t** _lf_shutdown_reactions = NULL;
int _lf_shutdown_reactions_size = 0;
// Array of pointers to reset triggers.
reaction_t** _lf_reset_reactions = NULL;
int _lf_reset_reactions_size = 0;
void _lf_initialize_trigger_objects() {
    // Initialize the _lf_clock
    lf_initialize_clock();
    // Create the array that will contain pointers to is_present fields to reset on each step.
    _lf_is_present_fields_size = 13;
    _lf_is_present_fields = (bool**)calloc(13, sizeof(bool*));
    if (_lf_is_present_fields == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated = (bool**)calloc(13, sizeof(bool*));
    if (_lf_is_present_fields_abbreviated == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated_size = 0;
    #ifdef FEDERATED_DECENTRALIZED
    // Create the array that will contain pointers to intended_tag fields to reset on each step.
    _lf_intended_tag_fields_size = 13;
    _lf_intended_tag_fields = (tag_t**)malloc(_lf_intended_tag_fields_size * sizeof(tag_t*));
    
    #endif // FEDERATED_DECENTRALIZED
    int _lf_startup_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_startup_reactions_count);
    int _lf_shutdown_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_shutdown_reactions_count);
    int _lf_reset_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_reset_reactions_count);
    int _lf_timer_triggers_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_timer_triggers_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    _server1436171503_main_main_self_t* server_main_self[1];
    SUPPRESS_UNUSED_WARNING(server_main_self);
    _serverreactor1598031955_self_t* server_server_self[1];
    SUPPRESS_UNUSED_WARNING(server_server_self);
    // ***** Start initializing Server of class Server
    server_main_self[0] = new_server1436171503_main();
    server_main_self[0]->_lf_name = "server_main_lf";
    // Initializing action Server.inputControlReactionTrigger
    server_main_self[0]->_lf__inputControlReactionTrigger.offset = 0;
    server_main_self[0]->_lf__inputControlReactionTrigger.period = -1;
    server_main_self[0]->_lf__inputControlReactionTrigger.mode = NULL;
    // Initializing action Server.networkMessage
    server_main_self[0]->_lf__networkMessage.offset = 0;
    server_main_self[0]->_lf__networkMessage.period = -1;
    server_main_self[0]->_lf__networkMessage.mode = NULL;
    // Initializing action Server.inputControlReactionTrigger_0
    server_main_self[0]->_lf__inputControlReactionTrigger_0.offset = 0;
    server_main_self[0]->_lf__inputControlReactionTrigger_0.period = -1;
    server_main_self[0]->_lf__inputControlReactionTrigger_0.mode = NULL;
    // Initializing action Server.networkMessage_0
    server_main_self[0]->_lf__networkMessage_0.offset = 0;
    server_main_self[0]->_lf__networkMessage_0.period = -1;
    server_main_self[0]->_lf__networkMessage_0.mode = NULL;
    // Initializing action Server.inputControlReactionTrigger_1
    server_main_self[0]->_lf__inputControlReactionTrigger_1.offset = 0;
    server_main_self[0]->_lf__inputControlReactionTrigger_1.period = -1;
    server_main_self[0]->_lf__inputControlReactionTrigger_1.mode = NULL;
    // Initializing action Server.networkMessage_1
    server_main_self[0]->_lf__networkMessage_1.offset = 0;
    server_main_self[0]->_lf__networkMessage_1.period = -1;
    server_main_self[0]->_lf__networkMessage_1.mode = NULL;
    // Initializing action Server.inputControlReactionTrigger_2
    server_main_self[0]->_lf__inputControlReactionTrigger_2.offset = 0;
    server_main_self[0]->_lf__inputControlReactionTrigger_2.period = -1;
    server_main_self[0]->_lf__inputControlReactionTrigger_2.mode = NULL;
    // Initializing action Server.networkMessage_2
    server_main_self[0]->_lf__networkMessage_2.offset = 0;
    server_main_self[0]->_lf__networkMessage_2.period = -1;
    server_main_self[0]->_lf__networkMessage_2.mode = NULL;
    _lf_initialize_template((token_template_t*)
            &(server_main_self[0]->_lf__inputControlReactionTrigger),
    0);
    server_main_self[0]->_lf__inputControlReactionTrigger.status = absent;
    _lf_initialize_template((token_template_t*)
            &(server_main_self[0]->_lf__networkMessage),
    0);
    server_main_self[0]->_lf__networkMessage.status = absent;
    _lf_initialize_template((token_template_t*)
            &(server_main_self[0]->_lf__inputControlReactionTrigger_0),
    0);
    server_main_self[0]->_lf__inputControlReactionTrigger_0.status = absent;
    _lf_initialize_template((token_template_t*)
            &(server_main_self[0]->_lf__networkMessage_0),
    0);
    server_main_self[0]->_lf__networkMessage_0.status = absent;
    _lf_initialize_template((token_template_t*)
            &(server_main_self[0]->_lf__inputControlReactionTrigger_1),
    0);
    server_main_self[0]->_lf__inputControlReactionTrigger_1.status = absent;
    _lf_initialize_template((token_template_t*)
            &(server_main_self[0]->_lf__networkMessage_1),
    0);
    server_main_self[0]->_lf__networkMessage_1.status = absent;
    _lf_initialize_template((token_template_t*)
            &(server_main_self[0]->_lf__inputControlReactionTrigger_2),
    0);
    server_main_self[0]->_lf__inputControlReactionTrigger_2.status = absent;
    _lf_initialize_template((token_template_t*)
            &(server_main_self[0]->_lf__networkMessage_2),
    0);
    server_main_self[0]->_lf__networkMessage_2.status = absent;
    server_main_self[0]->_lf__reaction_0.deadline = NEVER;
    server_main_self[0]->_lf__reaction_1.deadline = NEVER;
    server_main_self[0]->_lf__reaction_2.deadline = NEVER;
    server_main_self[0]->_lf__reaction_3.deadline = NEVER;
    server_main_self[0]->_lf__reaction_4.deadline = NEVER;
    server_main_self[0]->_lf__reaction_5.deadline = NEVER;
    server_main_self[0]->_lf__reaction_6.deadline = NEVER;
    server_main_self[0]->_lf__reaction_7.deadline = NEVER;
    server_main_self[0]->_lf__reaction_8.deadline = NEVER;
    server_main_self[0]->_lf__reaction_9.deadline = NEVER;
    {
        // ***** Start initializing Server.Server of class ServerReactor
        server_server_self[0] = new_serverreactor1598031955();
        server_server_self[0]->_lf_name = "server_server_lf";
        server_server_self[0]->_lf_py_reaction_function_0 = 
        get_python_function("__main__", 
            server_server_self[0]->_lf_name,
            0,
            "reaction_function_0");
        if(server_server_self[0]->_lf_py_reaction_function_0 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_0");
        }
        server_server_self[0]->_lf_py_reaction_function_1 = 
        get_python_function("__main__", 
            server_server_self[0]->_lf_name,
            0,
            "reaction_function_1");
        if(server_server_self[0]->_lf_py_reaction_function_1 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_1");
        }
        // width of -2 indicates that it is not a multiport.
        server_server_self[0]->_lf_global_parameter_width = -2;
        server_server_self[0]->_lf_updated_parameters_width = 2;
        // Allocate memory for multiport inputs.
        server_server_self[0]->_lf_updated_parameters = (serverreactor1598031955_updated_parameters_t**)_lf_allocate(
                2, sizeof(serverreactor1598031955_updated_parameters_t*),
                &server_server_self[0]->base.allocations); 
        // Set inputs by default to an always absent default input.
        for (int i = 0; i < 2; i++) {
            server_server_self[0]->_lf_updated_parameters[i] = &server_server_self[0]->_lf_default__updated_parameters;
        }
        server_server_self[0]->_lf_num_train_samples_width = 2;
        // Allocate memory for multiport inputs.
        server_server_self[0]->_lf_num_train_samples = (serverreactor1598031955_num_train_samples_t**)_lf_allocate(
                2, sizeof(serverreactor1598031955_num_train_samples_t*),
                &server_server_self[0]->base.allocations); 
        // Set inputs by default to an always absent default input.
        for (int i = 0; i < 2; i++) {
            server_server_self[0]->_lf_num_train_samples[i] = &server_server_self[0]->_lf_default__num_train_samples;
        }
        _lf_startup_reactions[_lf_startup_reactions_count++] = &server_server_self[0]->_lf__reaction_0;
        server_server_self[0]->_lf__reaction_0.deadline = NEVER;
        server_server_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing Server.Server
    }
    //***** End initializing Server
    // **** Start deferred initialize for Server
    {
        // A reaction writes to a multiport of a child. Allocate memory.
        {
            server_main_self[0]->_lf_Server.updated_parameters_width = 2;
            // Allocate memory to store output of reaction feeding 
            // a multiport input of a contained reactor.
            server_main_self[0]->_lf_Server.updated_parameters = (serverreactor1598031955_updated_parameters_t**)_lf_allocate(
                    2, sizeof(serverreactor1598031955_updated_parameters_t*),
                    &server_main_self[0]->base.allocations); 
            for (int i = 0; i < 2; i++) {
                server_main_self[0]->_lf_Server.updated_parameters[i] = (serverreactor1598031955_updated_parameters_t*)_lf_allocate(
                        1, sizeof(serverreactor1598031955_updated_parameters_t),
                        &server_main_self[0]->base.allocations); 
            }
        }
        // A reaction writes to a multiport of a child. Allocate memory.
        {
            server_main_self[0]->_lf_Server.num_train_samples_width = 2;
            // Allocate memory to store output of reaction feeding 
            // a multiport input of a contained reactor.
            server_main_self[0]->_lf_Server.num_train_samples = (serverreactor1598031955_num_train_samples_t**)_lf_allocate(
                    2, sizeof(serverreactor1598031955_num_train_samples_t*),
                    &server_main_self[0]->base.allocations); 
            for (int i = 0; i < 2; i++) {
                server_main_self[0]->_lf_Server.num_train_samples[i] = (serverreactor1598031955_num_train_samples_t*)_lf_allocate(
                        1, sizeof(serverreactor1598031955_num_train_samples_t),
                        &server_main_self[0]->base.allocations); 
            }
        }
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of Server.
        server_main_self[0]->_lf__reaction_0.num_outputs = 2;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        server_main_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                2, sizeof(trigger_t**),
                &server_main_self[0]->base.allocations);
        server_main_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                2, sizeof(int),
                &server_main_self[0]->base.allocations);
        server_main_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                2, sizeof(bool*),
                &server_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                for (int i = 0; i < 2; i++) {
                    server_main_self[0]->_lf__reaction_0.output_produced[i + count]
                            = &server_main_self[0]->_lf_Server.updated_parameters[i]->is_present;
                }
                count += 2;
            }
        }
        
        // ** End initialization for reaction 0 of Server
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of Server.
        server_main_self[0]->_lf__reaction_1.num_outputs = 2;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        server_main_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                2, sizeof(trigger_t**),
                &server_main_self[0]->base.allocations);
        server_main_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                2, sizeof(int),
                &server_main_self[0]->base.allocations);
        server_main_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                2, sizeof(bool*),
                &server_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                for (int i = 0; i < 2; i++) {
                    server_main_self[0]->_lf__reaction_1.output_produced[i + count]
                            = &server_main_self[0]->_lf_Server.updated_parameters[i]->is_present;
                }
                count += 2;
            }
        }
        
        // ** End initialization for reaction 1 of Server
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_2 of Server.
        server_main_self[0]->_lf__reaction_2.num_outputs = 2;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        server_main_self[0]->_lf__reaction_2.triggers = (trigger_t***)_lf_allocate(
                2, sizeof(trigger_t**),
                &server_main_self[0]->base.allocations);
        server_main_self[0]->_lf__reaction_2.triggered_sizes = (int*)_lf_allocate(
                2, sizeof(int),
                &server_main_self[0]->base.allocations);
        server_main_self[0]->_lf__reaction_2.output_produced = (bool**)_lf_allocate(
                2, sizeof(bool*),
                &server_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                for (int i = 0; i < 2; i++) {
                    server_main_self[0]->_lf__reaction_2.output_produced[i + count]
                            = &server_main_self[0]->_lf_Server.num_train_samples[i]->is_present;
                }
                count += 2;
            }
        }
        
        // ** End initialization for reaction 2 of Server
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_3 of Server.
        server_main_self[0]->_lf__reaction_3.num_outputs = 2;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        server_main_self[0]->_lf__reaction_3.triggers = (trigger_t***)_lf_allocate(
                2, sizeof(trigger_t**),
                &server_main_self[0]->base.allocations);
        server_main_self[0]->_lf__reaction_3.triggered_sizes = (int*)_lf_allocate(
                2, sizeof(int),
                &server_main_self[0]->base.allocations);
        server_main_self[0]->_lf__reaction_3.output_produced = (bool**)_lf_allocate(
                2, sizeof(bool*),
                &server_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                for (int i = 0; i < 2; i++) {
                    server_main_self[0]->_lf__reaction_3.output_produced[i + count]
                            = &server_main_self[0]->_lf_Server.num_train_samples[i]->is_present;
                }
                count += 2;
            }
        }
        
        // ** End initialization for reaction 3 of Server
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_4 of Server.
        server_main_self[0]->_lf__reaction_4.num_outputs = 2;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        server_main_self[0]->_lf__reaction_4.triggers = (trigger_t***)_lf_allocate(
                2, sizeof(trigger_t**),
                &server_main_self[0]->base.allocations);
        server_main_self[0]->_lf__reaction_4.triggered_sizes = (int*)_lf_allocate(
                2, sizeof(int),
                &server_main_self[0]->base.allocations);
        server_main_self[0]->_lf__reaction_4.output_produced = (bool**)_lf_allocate(
                2, sizeof(bool*),
                &server_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                for (int i = 0; i < 2; i++) {
                    server_main_self[0]->_lf__reaction_4.output_produced[i + count]
                            = &server_main_self[0]->_lf_Server.updated_parameters[i]->is_present;
                }
                count += 2;
            }
        }
        
        // ** End initialization for reaction 4 of Server
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_5 of Server.
        server_main_self[0]->_lf__reaction_5.num_outputs = 2;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        server_main_self[0]->_lf__reaction_5.triggers = (trigger_t***)_lf_allocate(
                2, sizeof(trigger_t**),
                &server_main_self[0]->base.allocations);
        server_main_self[0]->_lf__reaction_5.triggered_sizes = (int*)_lf_allocate(
                2, sizeof(int),
                &server_main_self[0]->base.allocations);
        server_main_self[0]->_lf__reaction_5.output_produced = (bool**)_lf_allocate(
                2, sizeof(bool*),
                &server_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                for (int i = 0; i < 2; i++) {
                    server_main_self[0]->_lf__reaction_5.output_produced[i + count]
                            = &server_main_self[0]->_lf_Server.updated_parameters[i]->is_present;
                }
                count += 2;
            }
        }
        
        // ** End initialization for reaction 5 of Server
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_6 of Server.
        server_main_self[0]->_lf__reaction_6.num_outputs = 2;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        server_main_self[0]->_lf__reaction_6.triggers = (trigger_t***)_lf_allocate(
                2, sizeof(trigger_t**),
                &server_main_self[0]->base.allocations);
        server_main_self[0]->_lf__reaction_6.triggered_sizes = (int*)_lf_allocate(
                2, sizeof(int),
                &server_main_self[0]->base.allocations);
        server_main_self[0]->_lf__reaction_6.output_produced = (bool**)_lf_allocate(
                2, sizeof(bool*),
                &server_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                for (int i = 0; i < 2; i++) {
                    server_main_self[0]->_lf__reaction_6.output_produced[i + count]
                            = &server_main_self[0]->_lf_Server.num_train_samples[i]->is_present;
                }
                count += 2;
            }
        }
        
        // ** End initialization for reaction 6 of Server
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_7 of Server.
        server_main_self[0]->_lf__reaction_7.num_outputs = 2;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        server_main_self[0]->_lf__reaction_7.triggers = (trigger_t***)_lf_allocate(
                2, sizeof(trigger_t**),
                &server_main_self[0]->base.allocations);
        server_main_self[0]->_lf__reaction_7.triggered_sizes = (int*)_lf_allocate(
                2, sizeof(int),
                &server_main_self[0]->base.allocations);
        server_main_self[0]->_lf__reaction_7.output_produced = (bool**)_lf_allocate(
                2, sizeof(bool*),
                &server_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                for (int i = 0; i < 2; i++) {
                    server_main_self[0]->_lf__reaction_7.output_produced[i + count]
                            = &server_main_self[0]->_lf_Server.num_train_samples[i]->is_present;
                }
                count += 2;
            }
        }
        
        // ** End initialization for reaction 7 of Server
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_8 of Server.
        server_main_self[0]->_lf__reaction_8.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 8 of Server
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_9 of Server.
        server_main_self[0]->_lf__reaction_9.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 9 of Server
        // **** Start deferred initialize for Server.Server
        {
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of Server.Server.
            server_server_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            server_server_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &server_server_self[0]->base.allocations);
            server_server_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &server_server_self[0]->base.allocations);
            server_server_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &server_server_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    server_server_self[0]->_lf__reaction_0.output_produced[count++] = &server_server_self[0]->_lf_global_parameter.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of Server.Server
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of Server.Server.
            server_server_self[0]->_lf__reaction_1.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            server_server_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &server_server_self[0]->base.allocations);
            server_server_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &server_server_self[0]->base.allocations);
            server_server_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &server_server_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    server_server_self[0]->_lf__reaction_1.output_produced[count++] = &server_server_self[0]->_lf_global_parameter.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of Server.Server
        }
        // **** End of deferred initialize for Server.Server
    }
    // **** End of deferred initialize for Server
    // **** Start non-nested deferred initialize for Server
    // Set number of destination reactors for port Server.updated_parameters.
    // Iterate over range Server.Server.updated_parameters(0,2)->[Server.Server.updated_parameters(0,2)].
    {
        int range_start[] =  { 0, 0 };
        int range_radixes[] = { 2, 1 };
        int permutation[] = { 0, 1 };
        mixed_radix_int_t range_mr = {
            2,
            range_start,
            range_radixes,
            permutation
        };
        for (int range_count = 0; range_count < 0 + 2; range_count++) {
            int src_runtime = mixed_radix_parent(&range_mr, 2); // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = range_mr.digits[0]; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = range_mr.digits[1]; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            server_main_self[src_runtime]->_lf_Server.updated_parameters[src_channel]->num_destinations = 1;
            mixed_radix_incr(&range_mr);
        }
    }
    // Set number of destination reactors for port Server.num_train_samples.
    // Iterate over range Server.Server.num_train_samples(0,2)->[Server.Server.num_train_samples(0,2)].
    {
        int range_start[] =  { 0, 0 };
        int range_radixes[] = { 2, 1 };
        int permutation[] = { 0, 1 };
        mixed_radix_int_t range_mr = {
            2,
            range_start,
            range_radixes,
            permutation
        };
        for (int range_count = 0; range_count < 0 + 2; range_count++) {
            int src_runtime = mixed_radix_parent(&range_mr, 2); // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = range_mr.digits[0]; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = range_mr.digits[1]; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            server_main_self[src_runtime]->_lf_Server.num_train_samples[src_channel]->num_destinations = 1;
            mixed_radix_incr(&range_mr);
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range Server.Server.updated_parameters(0,2)->[Server.Server.updated_parameters(0,2)].
        {
            int range_start[] =  { 0, 0 };
            int range_radixes[] = { 2, 1 };
            int permutation[] = { 0, 1 };
            mixed_radix_int_t range_mr = {
                2,
                range_start,
                range_radixes,
                permutation
            };
            for (int range_count = 0; range_count < 0 + 2; range_count++) {
                int src_runtime = mixed_radix_parent(&range_mr, 2); // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = range_mr.digits[0]; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = range_mr.digits[1]; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Reaction 0 of Server triggers 1 downstream reactions
                // through port Server.Server.updated_parameters.
                server_main_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 0 of Server, allocate an
                // array of trigger pointers for downstream reactions through port Server.Server.updated_parameters
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &server_main_self[src_runtime]->base.allocations); 
                server_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
                mixed_radix_incr(&range_mr);
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges Server.Server.updated_parameters(0,2)->[Server.Server.updated_parameters(0,2)] and Server.Server.updated_parameters(0,2).
        {
            int src_start[] =  { 0, 0 };
            int src_value[] =  { 0, 0 }; // Will be incremented.
            int src_radixes[] = { 2, 1 };
            int src_permutation[] = { 0, 1 };
            mixed_radix_int_t src_range_mr = {
                2,
                src_value,
                src_radixes,
                src_permutation
            };
            // Iterate over range Server.Server.updated_parameters(0,2).
            {
                int range_start[] =  { 0, 0 };
                int range_radixes[] = { 2, 1 };
                int permutation[] = { 0, 1 };
                mixed_radix_int_t range_mr = {
                    2,
                    range_start,
                    range_radixes,
                    permutation
                };
                for (int range_count = 0; range_count < 0 + 2; range_count++) {
                    int dst_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
                    SUPPRESS_UNUSED_WARNING(dst_runtime);
                    int dst_channel = range_mr.digits[0]; // Channel index.
                    SUPPRESS_UNUSED_WARNING(dst_channel);
                    int dst_bank = range_mr.digits[1]; // Bank index.
                    SUPPRESS_UNUSED_WARNING(dst_bank);
                    int src_runtime = mixed_radix_parent(&src_range_mr, 2); // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = src_range_mr.digits[0]; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = src_range_mr.digits[1]; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Point to destination port Server.Server.updated_parameters's trigger struct.
                    server_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &server_server_self[dst_runtime]->_lf__updated_parameters;
                    mixed_radix_incr(&src_range_mr);
                    if (mixed_radix_to_int(&src_range_mr) >= 0 + 2) {
                        // Start over with the source.
                        for (int i = 0; i < src_range_mr.size; i++) {
                            src_range_mr.digits[i] = src_start[i];
                        }
                    }
                    mixed_radix_incr(&range_mr);
                }
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range Server.Server.updated_parameters(0,2)->[Server.Server.updated_parameters(0,2)].
        {
            int range_start[] =  { 0, 0 };
            int range_radixes[] = { 2, 1 };
            int permutation[] = { 0, 1 };
            mixed_radix_int_t range_mr = {
                2,
                range_start,
                range_radixes,
                permutation
            };
            for (int range_count = 0; range_count < 0 + 2; range_count++) {
                int src_runtime = mixed_radix_parent(&range_mr, 2); // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = range_mr.digits[0]; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = range_mr.digits[1]; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Reaction 1 of Server triggers 1 downstream reactions
                // through port Server.Server.updated_parameters.
                server_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 1 of Server, allocate an
                // array of trigger pointers for downstream reactions through port Server.Server.updated_parameters
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &server_main_self[src_runtime]->base.allocations); 
                server_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
                mixed_radix_incr(&range_mr);
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges Server.Server.updated_parameters(0,2)->[Server.Server.updated_parameters(0,2)] and Server.Server.updated_parameters(0,2).
        {
            int src_start[] =  { 0, 0 };
            int src_value[] =  { 0, 0 }; // Will be incremented.
            int src_radixes[] = { 2, 1 };
            int src_permutation[] = { 0, 1 };
            mixed_radix_int_t src_range_mr = {
                2,
                src_value,
                src_radixes,
                src_permutation
            };
            // Iterate over range Server.Server.updated_parameters(0,2).
            {
                int range_start[] =  { 0, 0 };
                int range_radixes[] = { 2, 1 };
                int permutation[] = { 0, 1 };
                mixed_radix_int_t range_mr = {
                    2,
                    range_start,
                    range_radixes,
                    permutation
                };
                for (int range_count = 0; range_count < 0 + 2; range_count++) {
                    int dst_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
                    SUPPRESS_UNUSED_WARNING(dst_runtime);
                    int dst_channel = range_mr.digits[0]; // Channel index.
                    SUPPRESS_UNUSED_WARNING(dst_channel);
                    int dst_bank = range_mr.digits[1]; // Bank index.
                    SUPPRESS_UNUSED_WARNING(dst_bank);
                    int src_runtime = mixed_radix_parent(&src_range_mr, 2); // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = src_range_mr.digits[0]; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = src_range_mr.digits[1]; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Point to destination port Server.Server.updated_parameters's trigger struct.
                    server_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &server_server_self[dst_runtime]->_lf__updated_parameters;
                    mixed_radix_incr(&src_range_mr);
                    if (mixed_radix_to_int(&src_range_mr) >= 0 + 2) {
                        // Start over with the source.
                        for (int i = 0; i < src_range_mr.size; i++) {
                            src_range_mr.digits[i] = src_start[i];
                        }
                    }
                    mixed_radix_incr(&range_mr);
                }
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range Server.Server.num_train_samples(0,2)->[Server.Server.num_train_samples(0,2)].
        {
            int range_start[] =  { 0, 0 };
            int range_radixes[] = { 2, 1 };
            int permutation[] = { 0, 1 };
            mixed_radix_int_t range_mr = {
                2,
                range_start,
                range_radixes,
                permutation
            };
            for (int range_count = 0; range_count < 0 + 2; range_count++) {
                int src_runtime = mixed_radix_parent(&range_mr, 2); // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = range_mr.digits[0]; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = range_mr.digits[1]; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Reaction 2 of Server triggers 1 downstream reactions
                // through port Server.Server.num_train_samples.
                server_main_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 2 of Server, allocate an
                // array of trigger pointers for downstream reactions through port Server.Server.num_train_samples
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &server_main_self[src_runtime]->base.allocations); 
                server_main_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
                mixed_radix_incr(&range_mr);
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges Server.Server.num_train_samples(0,2)->[Server.Server.num_train_samples(0,2)] and Server.Server.num_train_samples(0,2).
        {
            int src_start[] =  { 0, 0 };
            int src_value[] =  { 0, 0 }; // Will be incremented.
            int src_radixes[] = { 2, 1 };
            int src_permutation[] = { 0, 1 };
            mixed_radix_int_t src_range_mr = {
                2,
                src_value,
                src_radixes,
                src_permutation
            };
            // Iterate over range Server.Server.num_train_samples(0,2).
            {
                int range_start[] =  { 0, 0 };
                int range_radixes[] = { 2, 1 };
                int permutation[] = { 0, 1 };
                mixed_radix_int_t range_mr = {
                    2,
                    range_start,
                    range_radixes,
                    permutation
                };
                for (int range_count = 0; range_count < 0 + 2; range_count++) {
                    int dst_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
                    SUPPRESS_UNUSED_WARNING(dst_runtime);
                    int dst_channel = range_mr.digits[0]; // Channel index.
                    SUPPRESS_UNUSED_WARNING(dst_channel);
                    int dst_bank = range_mr.digits[1]; // Bank index.
                    SUPPRESS_UNUSED_WARNING(dst_bank);
                    int src_runtime = mixed_radix_parent(&src_range_mr, 2); // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = src_range_mr.digits[0]; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = src_range_mr.digits[1]; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Point to destination port Server.Server.num_train_samples's trigger struct.
                    server_main_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &server_server_self[dst_runtime]->_lf__num_train_samples;
                    mixed_radix_incr(&src_range_mr);
                    if (mixed_radix_to_int(&src_range_mr) >= 0 + 2) {
                        // Start over with the source.
                        for (int i = 0; i < src_range_mr.size; i++) {
                            src_range_mr.digits[i] = src_start[i];
                        }
                    }
                    mixed_radix_incr(&range_mr);
                }
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range Server.Server.num_train_samples(0,2)->[Server.Server.num_train_samples(0,2)].
        {
            int range_start[] =  { 0, 0 };
            int range_radixes[] = { 2, 1 };
            int permutation[] = { 0, 1 };
            mixed_radix_int_t range_mr = {
                2,
                range_start,
                range_radixes,
                permutation
            };
            for (int range_count = 0; range_count < 0 + 2; range_count++) {
                int src_runtime = mixed_radix_parent(&range_mr, 2); // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = range_mr.digits[0]; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = range_mr.digits[1]; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Reaction 3 of Server triggers 1 downstream reactions
                // through port Server.Server.num_train_samples.
                server_main_self[src_runtime]->_lf__reaction_3.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 3 of Server, allocate an
                // array of trigger pointers for downstream reactions through port Server.Server.num_train_samples
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &server_main_self[src_runtime]->base.allocations); 
                server_main_self[src_runtime]->_lf__reaction_3.triggers[triggers_index[src_runtime]++] = trigger_array;
                mixed_radix_incr(&range_mr);
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges Server.Server.num_train_samples(0,2)->[Server.Server.num_train_samples(0,2)] and Server.Server.num_train_samples(0,2).
        {
            int src_start[] =  { 0, 0 };
            int src_value[] =  { 0, 0 }; // Will be incremented.
            int src_radixes[] = { 2, 1 };
            int src_permutation[] = { 0, 1 };
            mixed_radix_int_t src_range_mr = {
                2,
                src_value,
                src_radixes,
                src_permutation
            };
            // Iterate over range Server.Server.num_train_samples(0,2).
            {
                int range_start[] =  { 0, 0 };
                int range_radixes[] = { 2, 1 };
                int permutation[] = { 0, 1 };
                mixed_radix_int_t range_mr = {
                    2,
                    range_start,
                    range_radixes,
                    permutation
                };
                for (int range_count = 0; range_count < 0 + 2; range_count++) {
                    int dst_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
                    SUPPRESS_UNUSED_WARNING(dst_runtime);
                    int dst_channel = range_mr.digits[0]; // Channel index.
                    SUPPRESS_UNUSED_WARNING(dst_channel);
                    int dst_bank = range_mr.digits[1]; // Bank index.
                    SUPPRESS_UNUSED_WARNING(dst_bank);
                    int src_runtime = mixed_radix_parent(&src_range_mr, 2); // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = src_range_mr.digits[0]; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = src_range_mr.digits[1]; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Point to destination port Server.Server.num_train_samples's trigger struct.
                    server_main_self[src_runtime]->_lf__reaction_3.triggers[triggers_index[src_runtime] + src_channel][0] = &server_server_self[dst_runtime]->_lf__num_train_samples;
                    mixed_radix_incr(&src_range_mr);
                    if (mixed_radix_to_int(&src_range_mr) >= 0 + 2) {
                        // Start over with the source.
                        for (int i = 0; i < src_range_mr.size; i++) {
                            src_range_mr.digits[i] = src_start[i];
                        }
                    }
                    mixed_radix_incr(&range_mr);
                }
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range Server.Server.updated_parameters(0,2)->[Server.Server.updated_parameters(0,2)].
        {
            int range_start[] =  { 0, 0 };
            int range_radixes[] = { 2, 1 };
            int permutation[] = { 0, 1 };
            mixed_radix_int_t range_mr = {
                2,
                range_start,
                range_radixes,
                permutation
            };
            for (int range_count = 0; range_count < 0 + 2; range_count++) {
                int src_runtime = mixed_radix_parent(&range_mr, 2); // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = range_mr.digits[0]; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = range_mr.digits[1]; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Reaction 4 of Server triggers 1 downstream reactions
                // through port Server.Server.updated_parameters.
                server_main_self[src_runtime]->_lf__reaction_4.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 4 of Server, allocate an
                // array of trigger pointers for downstream reactions through port Server.Server.updated_parameters
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &server_main_self[src_runtime]->base.allocations); 
                server_main_self[src_runtime]->_lf__reaction_4.triggers[triggers_index[src_runtime]++] = trigger_array;
                mixed_radix_incr(&range_mr);
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges Server.Server.updated_parameters(0,2)->[Server.Server.updated_parameters(0,2)] and Server.Server.updated_parameters(0,2).
        {
            int src_start[] =  { 0, 0 };
            int src_value[] =  { 0, 0 }; // Will be incremented.
            int src_radixes[] = { 2, 1 };
            int src_permutation[] = { 0, 1 };
            mixed_radix_int_t src_range_mr = {
                2,
                src_value,
                src_radixes,
                src_permutation
            };
            // Iterate over range Server.Server.updated_parameters(0,2).
            {
                int range_start[] =  { 0, 0 };
                int range_radixes[] = { 2, 1 };
                int permutation[] = { 0, 1 };
                mixed_radix_int_t range_mr = {
                    2,
                    range_start,
                    range_radixes,
                    permutation
                };
                for (int range_count = 0; range_count < 0 + 2; range_count++) {
                    int dst_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
                    SUPPRESS_UNUSED_WARNING(dst_runtime);
                    int dst_channel = range_mr.digits[0]; // Channel index.
                    SUPPRESS_UNUSED_WARNING(dst_channel);
                    int dst_bank = range_mr.digits[1]; // Bank index.
                    SUPPRESS_UNUSED_WARNING(dst_bank);
                    int src_runtime = mixed_radix_parent(&src_range_mr, 2); // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = src_range_mr.digits[0]; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = src_range_mr.digits[1]; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Point to destination port Server.Server.updated_parameters's trigger struct.
                    server_main_self[src_runtime]->_lf__reaction_4.triggers[triggers_index[src_runtime] + src_channel][0] = &server_server_self[dst_runtime]->_lf__updated_parameters;
                    mixed_radix_incr(&src_range_mr);
                    if (mixed_radix_to_int(&src_range_mr) >= 0 + 2) {
                        // Start over with the source.
                        for (int i = 0; i < src_range_mr.size; i++) {
                            src_range_mr.digits[i] = src_start[i];
                        }
                    }
                    mixed_radix_incr(&range_mr);
                }
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range Server.Server.updated_parameters(0,2)->[Server.Server.updated_parameters(0,2)].
        {
            int range_start[] =  { 0, 0 };
            int range_radixes[] = { 2, 1 };
            int permutation[] = { 0, 1 };
            mixed_radix_int_t range_mr = {
                2,
                range_start,
                range_radixes,
                permutation
            };
            for (int range_count = 0; range_count < 0 + 2; range_count++) {
                int src_runtime = mixed_radix_parent(&range_mr, 2); // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = range_mr.digits[0]; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = range_mr.digits[1]; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Reaction 5 of Server triggers 1 downstream reactions
                // through port Server.Server.updated_parameters.
                server_main_self[src_runtime]->_lf__reaction_5.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 5 of Server, allocate an
                // array of trigger pointers for downstream reactions through port Server.Server.updated_parameters
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &server_main_self[src_runtime]->base.allocations); 
                server_main_self[src_runtime]->_lf__reaction_5.triggers[triggers_index[src_runtime]++] = trigger_array;
                mixed_radix_incr(&range_mr);
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges Server.Server.updated_parameters(0,2)->[Server.Server.updated_parameters(0,2)] and Server.Server.updated_parameters(0,2).
        {
            int src_start[] =  { 0, 0 };
            int src_value[] =  { 0, 0 }; // Will be incremented.
            int src_radixes[] = { 2, 1 };
            int src_permutation[] = { 0, 1 };
            mixed_radix_int_t src_range_mr = {
                2,
                src_value,
                src_radixes,
                src_permutation
            };
            // Iterate over range Server.Server.updated_parameters(0,2).
            {
                int range_start[] =  { 0, 0 };
                int range_radixes[] = { 2, 1 };
                int permutation[] = { 0, 1 };
                mixed_radix_int_t range_mr = {
                    2,
                    range_start,
                    range_radixes,
                    permutation
                };
                for (int range_count = 0; range_count < 0 + 2; range_count++) {
                    int dst_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
                    SUPPRESS_UNUSED_WARNING(dst_runtime);
                    int dst_channel = range_mr.digits[0]; // Channel index.
                    SUPPRESS_UNUSED_WARNING(dst_channel);
                    int dst_bank = range_mr.digits[1]; // Bank index.
                    SUPPRESS_UNUSED_WARNING(dst_bank);
                    int src_runtime = mixed_radix_parent(&src_range_mr, 2); // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = src_range_mr.digits[0]; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = src_range_mr.digits[1]; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Point to destination port Server.Server.updated_parameters's trigger struct.
                    server_main_self[src_runtime]->_lf__reaction_5.triggers[triggers_index[src_runtime] + src_channel][0] = &server_server_self[dst_runtime]->_lf__updated_parameters;
                    mixed_radix_incr(&src_range_mr);
                    if (mixed_radix_to_int(&src_range_mr) >= 0 + 2) {
                        // Start over with the source.
                        for (int i = 0; i < src_range_mr.size; i++) {
                            src_range_mr.digits[i] = src_start[i];
                        }
                    }
                    mixed_radix_incr(&range_mr);
                }
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range Server.Server.num_train_samples(0,2)->[Server.Server.num_train_samples(0,2)].
        {
            int range_start[] =  { 0, 0 };
            int range_radixes[] = { 2, 1 };
            int permutation[] = { 0, 1 };
            mixed_radix_int_t range_mr = {
                2,
                range_start,
                range_radixes,
                permutation
            };
            for (int range_count = 0; range_count < 0 + 2; range_count++) {
                int src_runtime = mixed_radix_parent(&range_mr, 2); // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = range_mr.digits[0]; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = range_mr.digits[1]; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Reaction 6 of Server triggers 1 downstream reactions
                // through port Server.Server.num_train_samples.
                server_main_self[src_runtime]->_lf__reaction_6.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 6 of Server, allocate an
                // array of trigger pointers for downstream reactions through port Server.Server.num_train_samples
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &server_main_self[src_runtime]->base.allocations); 
                server_main_self[src_runtime]->_lf__reaction_6.triggers[triggers_index[src_runtime]++] = trigger_array;
                mixed_radix_incr(&range_mr);
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges Server.Server.num_train_samples(0,2)->[Server.Server.num_train_samples(0,2)] and Server.Server.num_train_samples(0,2).
        {
            int src_start[] =  { 0, 0 };
            int src_value[] =  { 0, 0 }; // Will be incremented.
            int src_radixes[] = { 2, 1 };
            int src_permutation[] = { 0, 1 };
            mixed_radix_int_t src_range_mr = {
                2,
                src_value,
                src_radixes,
                src_permutation
            };
            // Iterate over range Server.Server.num_train_samples(0,2).
            {
                int range_start[] =  { 0, 0 };
                int range_radixes[] = { 2, 1 };
                int permutation[] = { 0, 1 };
                mixed_radix_int_t range_mr = {
                    2,
                    range_start,
                    range_radixes,
                    permutation
                };
                for (int range_count = 0; range_count < 0 + 2; range_count++) {
                    int dst_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
                    SUPPRESS_UNUSED_WARNING(dst_runtime);
                    int dst_channel = range_mr.digits[0]; // Channel index.
                    SUPPRESS_UNUSED_WARNING(dst_channel);
                    int dst_bank = range_mr.digits[1]; // Bank index.
                    SUPPRESS_UNUSED_WARNING(dst_bank);
                    int src_runtime = mixed_radix_parent(&src_range_mr, 2); // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = src_range_mr.digits[0]; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = src_range_mr.digits[1]; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Point to destination port Server.Server.num_train_samples's trigger struct.
                    server_main_self[src_runtime]->_lf__reaction_6.triggers[triggers_index[src_runtime] + src_channel][0] = &server_server_self[dst_runtime]->_lf__num_train_samples;
                    mixed_radix_incr(&src_range_mr);
                    if (mixed_radix_to_int(&src_range_mr) >= 0 + 2) {
                        // Start over with the source.
                        for (int i = 0; i < src_range_mr.size; i++) {
                            src_range_mr.digits[i] = src_start[i];
                        }
                    }
                    mixed_radix_incr(&range_mr);
                }
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range Server.Server.num_train_samples(0,2)->[Server.Server.num_train_samples(0,2)].
        {
            int range_start[] =  { 0, 0 };
            int range_radixes[] = { 2, 1 };
            int permutation[] = { 0, 1 };
            mixed_radix_int_t range_mr = {
                2,
                range_start,
                range_radixes,
                permutation
            };
            for (int range_count = 0; range_count < 0 + 2; range_count++) {
                int src_runtime = mixed_radix_parent(&range_mr, 2); // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = range_mr.digits[0]; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = range_mr.digits[1]; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Reaction 7 of Server triggers 1 downstream reactions
                // through port Server.Server.num_train_samples.
                server_main_self[src_runtime]->_lf__reaction_7.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 7 of Server, allocate an
                // array of trigger pointers for downstream reactions through port Server.Server.num_train_samples
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &server_main_self[src_runtime]->base.allocations); 
                server_main_self[src_runtime]->_lf__reaction_7.triggers[triggers_index[src_runtime]++] = trigger_array;
                mixed_radix_incr(&range_mr);
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges Server.Server.num_train_samples(0,2)->[Server.Server.num_train_samples(0,2)] and Server.Server.num_train_samples(0,2).
        {
            int src_start[] =  { 0, 0 };
            int src_value[] =  { 0, 0 }; // Will be incremented.
            int src_radixes[] = { 2, 1 };
            int src_permutation[] = { 0, 1 };
            mixed_radix_int_t src_range_mr = {
                2,
                src_value,
                src_radixes,
                src_permutation
            };
            // Iterate over range Server.Server.num_train_samples(0,2).
            {
                int range_start[] =  { 0, 0 };
                int range_radixes[] = { 2, 1 };
                int permutation[] = { 0, 1 };
                mixed_radix_int_t range_mr = {
                    2,
                    range_start,
                    range_radixes,
                    permutation
                };
                for (int range_count = 0; range_count < 0 + 2; range_count++) {
                    int dst_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
                    SUPPRESS_UNUSED_WARNING(dst_runtime);
                    int dst_channel = range_mr.digits[0]; // Channel index.
                    SUPPRESS_UNUSED_WARNING(dst_channel);
                    int dst_bank = range_mr.digits[1]; // Bank index.
                    SUPPRESS_UNUSED_WARNING(dst_bank);
                    int src_runtime = mixed_radix_parent(&src_range_mr, 2); // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = src_range_mr.digits[0]; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = src_range_mr.digits[1]; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Point to destination port Server.Server.num_train_samples's trigger struct.
                    server_main_self[src_runtime]->_lf__reaction_7.triggers[triggers_index[src_runtime] + src_channel][0] = &server_server_self[dst_runtime]->_lf__num_train_samples;
                    mixed_radix_incr(&src_range_mr);
                    if (mixed_radix_to_int(&src_range_mr) >= 0 + 2) {
                        // Start over with the source.
                        for (int i = 0; i < src_range_mr.size; i++) {
                            src_range_mr.digits[i] = src_start[i];
                        }
                    }
                    mixed_radix_incr(&range_mr);
                }
            }
        }
    }
    // **** Start non-nested deferred initialize for Server.Server
    // For reference counting, set num_destinations for port Server.Server.global_parameter.
    // Iterate over range Server.Server.global_parameter(0,1)->[Server.Server.global_parameter(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        server_server_self[src_runtime]->_lf_global_parameter.num_destinations = 1;
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range Server.Server.global_parameter(0,1)->[Server.Server.global_parameter(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 0 of Server.Server triggers 1 downstream reactions
            // through port Server.Server.global_parameter.
            server_server_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of Server.Server, allocate an
            // array of trigger pointers for downstream reactions through port Server.Server.global_parameter
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &server_server_self[src_runtime]->base.allocations); 
            server_server_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges Server.Server.global_parameter(0,1)->[Server.Server.global_parameter(0,1)] and Server.Server.global_parameter(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range Server.Server.global_parameter(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Port Server.Server.global_parameter has reactions in its parent's parent.
                // Point to the trigger struct for those reactions.
                server_server_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &server_main_self[dst_runtime]->_lf_Server.global_parameter_trigger;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range Server.Server.global_parameter(0,1)->[Server.Server.global_parameter(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of Server.Server triggers 1 downstream reactions
            // through port Server.Server.global_parameter.
            server_server_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of Server.Server, allocate an
            // array of trigger pointers for downstream reactions through port Server.Server.global_parameter
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &server_server_self[src_runtime]->base.allocations); 
            server_server_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges Server.Server.global_parameter(0,1)->[Server.Server.global_parameter(0,1)] and Server.Server.global_parameter(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range Server.Server.global_parameter(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Port Server.Server.global_parameter has reactions in its parent's parent.
                // Point to the trigger struct for those reactions.
                server_server_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &server_main_self[dst_runtime]->_lf_Server.global_parameter_trigger;
            }
        }
    }
    // **** End of non-nested deferred initialize for Server.Server
    // **** End of non-nested deferred initialize for Server
    // Connect inputs and outputs for reactor Server.
    // Connect inputs and outputs for reactor Server.Server.
    // Connect Server.Server.updated_parameters(0,2)->[Server.Server.updated_parameters(0,2)] to port Server.Server.updated_parameters(0,2)
    // Iterate over ranges Server.Server.updated_parameters(0,2)->[Server.Server.updated_parameters(0,2)] and Server.Server.updated_parameters(0,2).
    {
        int src_start[] =  { 0, 0 };
        int src_value[] =  { 0, 0 }; // Will be incremented.
        int src_radixes[] = { 2, 1 };
        int src_permutation[] = { 0, 1 };
        mixed_radix_int_t src_range_mr = {
            2,
            src_value,
            src_radixes,
            src_permutation
        };
        // Iterate over range Server.Server.updated_parameters(0,2).
        {
            int range_start[] =  { 0, 0 };
            int range_radixes[] = { 2, 1 };
            int permutation[] = { 0, 1 };
            mixed_radix_int_t range_mr = {
                2,
                range_start,
                range_radixes,
                permutation
            };
            for (int range_count = 0; range_count < 0 + 2; range_count++) {
                int dst_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
                SUPPRESS_UNUSED_WARNING(dst_runtime);
                int dst_channel = range_mr.digits[0]; // Channel index.
                SUPPRESS_UNUSED_WARNING(dst_channel);
                int dst_bank = range_mr.digits[1]; // Bank index.
                SUPPRESS_UNUSED_WARNING(dst_bank);
                int src_runtime = mixed_radix_parent(&src_range_mr, 2); // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = src_range_mr.digits[0]; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = src_range_mr.digits[1]; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                server_server_self[dst_runtime]->_lf_updated_parameters[dst_channel] = (serverreactor1598031955_updated_parameters_t*)server_main_self[src_runtime]->_lf_Server.updated_parameters[src_channel];
                mixed_radix_incr(&src_range_mr);
                if (mixed_radix_to_int(&src_range_mr) >= 0 + 2) {
                    // Start over with the source.
                    for (int i = 0; i < src_range_mr.size; i++) {
                        src_range_mr.digits[i] = src_start[i];
                    }
                }
                mixed_radix_incr(&range_mr);
            }
        }
    }
    // Connect Server.Server.num_train_samples(0,2)->[Server.Server.num_train_samples(0,2)] to port Server.Server.num_train_samples(0,2)
    // Iterate over ranges Server.Server.num_train_samples(0,2)->[Server.Server.num_train_samples(0,2)] and Server.Server.num_train_samples(0,2).
    {
        int src_start[] =  { 0, 0 };
        int src_value[] =  { 0, 0 }; // Will be incremented.
        int src_radixes[] = { 2, 1 };
        int src_permutation[] = { 0, 1 };
        mixed_radix_int_t src_range_mr = {
            2,
            src_value,
            src_radixes,
            src_permutation
        };
        // Iterate over range Server.Server.num_train_samples(0,2).
        {
            int range_start[] =  { 0, 0 };
            int range_radixes[] = { 2, 1 };
            int permutation[] = { 0, 1 };
            mixed_radix_int_t range_mr = {
                2,
                range_start,
                range_radixes,
                permutation
            };
            for (int range_count = 0; range_count < 0 + 2; range_count++) {
                int dst_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
                SUPPRESS_UNUSED_WARNING(dst_runtime);
                int dst_channel = range_mr.digits[0]; // Channel index.
                SUPPRESS_UNUSED_WARNING(dst_channel);
                int dst_bank = range_mr.digits[1]; // Bank index.
                SUPPRESS_UNUSED_WARNING(dst_bank);
                int src_runtime = mixed_radix_parent(&src_range_mr, 2); // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = src_range_mr.digits[0]; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = src_range_mr.digits[1]; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                server_server_self[dst_runtime]->_lf_num_train_samples[dst_channel] = (serverreactor1598031955_num_train_samples_t*)server_main_self[src_runtime]->_lf_Server.num_train_samples[src_channel];
                mixed_radix_incr(&src_range_mr);
                if (mixed_radix_to_int(&src_range_mr) >= 0 + 2) {
                    // Start over with the source.
                    for (int i = 0; i < src_range_mr.size; i++) {
                        src_range_mr.digits[i] = src_start[i];
                    }
                }
                mixed_radix_incr(&range_mr);
            }
        }
    }
    // Connect Server.Server.global_parameter(0,1)->[Server.Server.global_parameter(0,1)] to port Server.Server.global_parameter(0,1)
    // Iterate over ranges Server.Server.global_parameter(0,1)->[Server.Server.global_parameter(0,1)] and Server.Server.global_parameter(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range Server.Server.global_parameter(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            server_main_self[dst_runtime]->_lf_Server.global_parameter = (serverreactor1598031955_global_parameter_t*)&server_server_self[src_runtime]->_lf_global_parameter;
        }
    }
    {
    }
    // Add port Server.Server.updated_parameters to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                // Port Server.Server.updated_parameters is a multiport. Iterate over its channels.
                for (int server_server_updated_parameters_c = 0; server_server_updated_parameters_c < 2; server_server_updated_parameters_c++) {
                    _lf_is_present_fields[0 + count] = &server_main_self[0]->_lf_Server.updated_parameters[server_server_updated_parameters_c]->is_present;
                    #ifdef FEDERATED_DECENTRALIZED
                    _lf_intended_tag_fields[0 + count] = &server_main_self[0]->_lf_Server.updated_parameters[server_server_updated_parameters_c]->intended_tag;
                    #endif // FEDERATED_DECENTRALIZED
                    count++;
                }
            }
        }
    }
    // Add port Server.Server.num_train_samples to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                // Port Server.Server.num_train_samples is a multiport. Iterate over its channels.
                for (int server_server_num_train_samples_c = 0; server_server_num_train_samples_c < 2; server_server_num_train_samples_c++) {
                    _lf_is_present_fields[2 + count] = &server_main_self[0]->_lf_Server.num_train_samples[server_server_num_train_samples_c]->is_present;
                    #ifdef FEDERATED_DECENTRALIZED
                    _lf_intended_tag_fields[2 + count] = &server_main_self[0]->_lf_Server.num_train_samples[server_server_num_train_samples_c]->intended_tag;
                    #endif // FEDERATED_DECENTRALIZED
                    count++;
                }
            }
        }
    }
    {
        // Add action Server.inputControlReactionTrigger to array of is_present fields.
        _lf_is_present_fields[4] 
                = &server_main_self[0]->_lf_inputControlReactionTrigger.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action Server.inputControlReactionTrigger to array of intended_tag fields.
        _lf_intended_tag_fields[4] 
                = &server_main_self[0]->_lf_inputControlReactionTrigger.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action Server.networkMessage to array of is_present fields.
        _lf_is_present_fields[5] 
                = &server_main_self[0]->_lf_networkMessage.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action Server.networkMessage to array of intended_tag fields.
        _lf_intended_tag_fields[5] 
                = &server_main_self[0]->_lf_networkMessage.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action Server.inputControlReactionTrigger_0 to array of is_present fields.
        _lf_is_present_fields[6] 
                = &server_main_self[0]->_lf_inputControlReactionTrigger_0.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action Server.inputControlReactionTrigger_0 to array of intended_tag fields.
        _lf_intended_tag_fields[6] 
                = &server_main_self[0]->_lf_inputControlReactionTrigger_0.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action Server.networkMessage_0 to array of is_present fields.
        _lf_is_present_fields[7] 
                = &server_main_self[0]->_lf_networkMessage_0.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action Server.networkMessage_0 to array of intended_tag fields.
        _lf_intended_tag_fields[7] 
                = &server_main_self[0]->_lf_networkMessage_0.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action Server.inputControlReactionTrigger_1 to array of is_present fields.
        _lf_is_present_fields[8] 
                = &server_main_self[0]->_lf_inputControlReactionTrigger_1.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action Server.inputControlReactionTrigger_1 to array of intended_tag fields.
        _lf_intended_tag_fields[8] 
                = &server_main_self[0]->_lf_inputControlReactionTrigger_1.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action Server.networkMessage_1 to array of is_present fields.
        _lf_is_present_fields[9] 
                = &server_main_self[0]->_lf_networkMessage_1.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action Server.networkMessage_1 to array of intended_tag fields.
        _lf_intended_tag_fields[9] 
                = &server_main_self[0]->_lf_networkMessage_1.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action Server.inputControlReactionTrigger_2 to array of is_present fields.
        _lf_is_present_fields[10] 
                = &server_main_self[0]->_lf_inputControlReactionTrigger_2.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action Server.inputControlReactionTrigger_2 to array of intended_tag fields.
        _lf_intended_tag_fields[10] 
                = &server_main_self[0]->_lf_inputControlReactionTrigger_2.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action Server.networkMessage_2 to array of is_present fields.
        _lf_is_present_fields[11] 
                = &server_main_self[0]->_lf_networkMessage_2.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action Server.networkMessage_2 to array of intended_tag fields.
        _lf_intended_tag_fields[11] 
                = &server_main_self[0]->_lf_networkMessage_2.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port Server.Server.global_parameter to array of is_present fields.
            _lf_is_present_fields[12 + count] = &server_server_self[0]->_lf_global_parameter.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port Server.Server.global_parameter to array of intended_tag fields.
            _lf_intended_tag_fields[12 + count] = &server_server_self[0]->_lf_global_parameter.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    // Set reaction priorities for ReactorInstance Server
    {
        server_main_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        server_main_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
        server_main_self[0]->_lf__reaction_1.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        server_main_self[0]->_lf__reaction_1.index = 0xffffffffffff0000LL;
        server_main_self[0]->_lf__reaction_2.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        server_main_self[0]->_lf__reaction_2.index = 0xffffffffffff0000LL;
        server_main_self[0]->_lf__reaction_3.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        server_main_self[0]->_lf__reaction_3.index = 0xffffffffffff0000LL;
        server_main_self[0]->_lf__reaction_4.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        server_main_self[0]->_lf__reaction_4.index = 0xffffffffffff0000LL;
        server_main_self[0]->_lf__reaction_5.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        server_main_self[0]->_lf__reaction_5.index = 0xffffffffffff0000LL;
        server_main_self[0]->_lf__reaction_6.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        server_main_self[0]->_lf__reaction_6.index = 0xffffffffffff0000LL;
        server_main_self[0]->_lf__reaction_7.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        server_main_self[0]->_lf__reaction_7.index = 0xffffffffffff0000LL;
        server_main_self[0]->_lf__reaction_8.chain_id = 1;
        // index is the OR of level 2 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        server_main_self[0]->_lf__reaction_8.index = 0xffffffffffff0002LL;
        server_main_self[0]->_lf__reaction_9.chain_id = 1;
        // index is the OR of level 2 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        server_main_self[0]->_lf__reaction_9.index = 0xffffffffffff0002LL;
        // Set reaction priorities for ReactorInstance Server.Server
        {
            server_server_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            server_server_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            server_server_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            server_server_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
        }
    }
    // Initialize the scheduler
    size_t num_reactions_per_level[3] = 
        {9, 1, 2};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 3};
    lf_sched_init(
        (size_t)_lf_number_of_workers,
        &sched_params
    );
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble();
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void _lf_trigger_startup_reactions() {
    for (int i = 0; i < _lf_startup_reactions_size; i++) {
        if (_lf_startup_reactions[i] != NULL) {
            _lf_trigger_reaction(_lf_startup_reactions[i], -1);
        }
    }
}
void _lf_initialize_timers() {
}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED
}
bool _lf_trigger_shutdown_reactions() {
    return false;
}
#ifndef FEDERATED
void terminate_execution() {}
#endif
