#include <limits.h>
#include "include/core/platform.h"
#include "include/api/api.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/threaded/scheduler.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
int lf_reactor_c_main(int argc, const char* argv[]);
#include "include/core/federated/federate.h"
#include "include/core/federated/net_common.h"
#include "pythontarget.h"
// Code generated by the Lingua Franca compiler from:
// file://mnt/c/Users/jacky/Desktop/Federated_Learning/fed-gen/Main/src/client1.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/mnt/c/Users/jacky/Desktop/Federated_Learning/fed-gen/Main/src-gen/client1"
int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
const char* _lf_default_argv[] = { "dummy", "-k", "true" };
void _lf_set_default_command_line_options() {
        default_argc = 3;
        default_argv = _lf_default_argv;
}
#include "clientreactor463863444.h"
#include "client11188084129_main.h"
#include "include/_client1_preamble.h"
// Array of pointers to timer triggers to be scheduled in _lf_initialize_timers().
trigger_t** _lf_timer_triggers = NULL;
int _lf_timer_triggers_size = 0;
// Array of pointers to startup triggers.
reaction_t* _lf_startup_reactions[1];
int _lf_startup_reactions_size = 1;
// Array of pointers to shutdown triggers.
reaction_t** _lf_shutdown_reactions = NULL;
int _lf_shutdown_reactions_size = 0;
// Array of pointers to reset triggers.
reaction_t** _lf_reset_reactions = NULL;
int _lf_reset_reactions_size = 0;
void _lf_initialize_trigger_objects() {
    // Initialize the _lf_clock
    lf_initialize_clock();
    // Create the array that will contain pointers to is_present fields to reset on each step.
    _lf_is_present_fields_size = 5;
    _lf_is_present_fields = (bool**)calloc(5, sizeof(bool*));
    if (_lf_is_present_fields == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated = (bool**)calloc(5, sizeof(bool*));
    if (_lf_is_present_fields_abbreviated == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated_size = 0;
    #ifdef FEDERATED_DECENTRALIZED
    // Create the array that will contain pointers to intended_tag fields to reset on each step.
    _lf_intended_tag_fields_size = 5;
    _lf_intended_tag_fields = (tag_t**)malloc(_lf_intended_tag_fields_size * sizeof(tag_t*));
    
    #endif // FEDERATED_DECENTRALIZED
    int _lf_startup_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_startup_reactions_count);
    int _lf_shutdown_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_shutdown_reactions_count);
    int _lf_reset_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_reset_reactions_count);
    int _lf_timer_triggers_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_timer_triggers_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    _client11188084129_main_main_self_t* client1_main_self[1];
    SUPPRESS_UNUSED_WARNING(client1_main_self);
    _clientreactor463863444_self_t* client1_client1_self[1];
    SUPPRESS_UNUSED_WARNING(client1_client1_self);
    // ***** Start initializing client1 of class client1
    client1_main_self[0] = new_client11188084129_main();
    client1_main_self[0]->_lf_name = "client1_main_lf";
    // Initializing action client1.outputControlReactionTrigger
    client1_main_self[0]->_lf__outputControlReactionTrigger.offset = 0;
    client1_main_self[0]->_lf__outputControlReactionTrigger.period = -1;
    client1_main_self[0]->_lf__outputControlReactionTrigger.mode = NULL;
    // Initializing action client1.networkMessage_3
    client1_main_self[0]->_lf__networkMessage_3.offset = 0;
    client1_main_self[0]->_lf__networkMessage_3.period = -1;
    client1_main_self[0]->_lf__networkMessage_3.mode = NULL;
    _lf_initialize_template((token_template_t*)
            &(client1_main_self[0]->_lf__outputControlReactionTrigger),
    0);
    client1_main_self[0]->_lf__outputControlReactionTrigger.status = absent;
    _lf_initialize_template((token_template_t*)
            &(client1_main_self[0]->_lf__networkMessage_3),
    0);
    client1_main_self[0]->_lf__networkMessage_3.status = absent;
    client1_main_self[0]->_lf__reaction_0.deadline = NEVER;
    client1_main_self[0]->_lf__reaction_1.deadline = NEVER;
    client1_main_self[0]->_lf__reaction_2.deadline = NEVER;
    client1_main_self[0]->_lf__reaction_3.deadline = NEVER;
    client1_main_self[0]->_lf__reaction_4.deadline = NEVER;
    {
        // ***** Start initializing client1.client1 of class ClientReactor
        client1_client1_self[0] = new_clientreactor463863444();
        client1_client1_self[0]->_lf_name = "client1_client1_lf";
        client1_client1_self[0]->_lf_py_reaction_function_0 = 
        get_python_function("__main__", 
            client1_client1_self[0]->_lf_name,
            0,
            "reaction_function_0");
        if(client1_client1_self[0]->_lf_py_reaction_function_0 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_0");
        }
        client1_client1_self[0]->_lf_py_reaction_function_1 = 
        get_python_function("__main__", 
            client1_client1_self[0]->_lf_name,
            0,
            "reaction_function_1");
        if(client1_client1_self[0]->_lf_py_reaction_function_1 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_1");
        }
        // width of -2 indicates that it is not a multiport.
        client1_client1_self[0]->_lf_updated_parameters_width = -2;
        // width of -2 indicates that it is not a multiport.
        client1_client1_self[0]->_lf_num_train_samples_width = -2;
        // width of -2 indicates that it is not a multiport.
        client1_client1_self[0]->_lf_global_parameter_width = -2;
        _lf_startup_reactions[_lf_startup_reactions_count++] = &client1_client1_self[0]->_lf__reaction_0;
        client1_client1_self[0]->_lf__reaction_0.deadline = NEVER;
        client1_client1_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing client1.client1
    }
    //***** End initializing client1
    // **** Start deferred initialize for client1
    {
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of client1.
        client1_main_self[0]->_lf__reaction_0.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 0 of client1
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of client1.
        client1_main_self[0]->_lf__reaction_1.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 1 of client1
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_2 of client1.
        client1_main_self[0]->_lf__reaction_2.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 2 of client1
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_3 of client1.
        client1_main_self[0]->_lf__reaction_3.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 3 of client1
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_4 of client1.
        client1_main_self[0]->_lf__reaction_4.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        client1_main_self[0]->_lf__reaction_4.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &client1_main_self[0]->base.allocations);
        client1_main_self[0]->_lf__reaction_4.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &client1_main_self[0]->base.allocations);
        client1_main_self[0]->_lf__reaction_4.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &client1_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                client1_main_self[0]->_lf__reaction_4.output_produced[count++] = &client1_main_self[0]->_lf_client1.global_parameter.is_present;
            }
        }
        
        // ** End initialization for reaction 4 of client1
        // **** Start deferred initialize for client1.client1
        {
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of client1.client1.
            client1_client1_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of client1.client1
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of client1.client1.
            client1_client1_self[0]->_lf__reaction_1.num_outputs = 2;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            client1_client1_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    2, sizeof(trigger_t**),
                    &client1_client1_self[0]->base.allocations);
            client1_client1_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    2, sizeof(int),
                    &client1_client1_self[0]->base.allocations);
            client1_client1_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    2, sizeof(bool*),
                    &client1_client1_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    client1_client1_self[0]->_lf__reaction_1.output_produced[count++] = &client1_client1_self[0]->_lf_updated_parameters.is_present;
                }
                {
                    client1_client1_self[0]->_lf__reaction_1.output_produced[count++] = &client1_client1_self[0]->_lf_num_train_samples.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of client1.client1
        }
        // **** End of deferred initialize for client1.client1
    }
    // **** End of deferred initialize for client1
    // **** Start non-nested deferred initialize for client1
    // Set number of destination reactors for port client1.global_parameter.
    // Iterate over range client1.client1.global_parameter(0,1)->[client1.client1.global_parameter(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        client1_main_self[src_runtime]->_lf_client1.global_parameter.num_destinations = 1;
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range client1.client1.global_parameter(0,1)->[client1.client1.global_parameter(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 4 of client1 triggers 1 downstream reactions
            // through port client1.client1.global_parameter.
            client1_main_self[src_runtime]->_lf__reaction_4.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 4 of client1, allocate an
            // array of trigger pointers for downstream reactions through port client1.client1.global_parameter
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &client1_main_self[src_runtime]->base.allocations); 
            client1_main_self[src_runtime]->_lf__reaction_4.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges client1.client1.global_parameter(0,1)->[client1.client1.global_parameter(0,1)] and client1.client1.global_parameter(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range client1.client1.global_parameter(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port client1.client1.global_parameter's trigger struct.
                client1_main_self[src_runtime]->_lf__reaction_4.triggers[triggers_index[src_runtime] + src_channel][0] = &client1_client1_self[dst_runtime]->_lf__global_parameter;
            }
        }
    }
    // **** Start non-nested deferred initialize for client1.client1
    // For reference counting, set num_destinations for port client1.client1.updated_parameters.
    // Iterate over range client1.client1.updated_parameters(0,1)->[client1.client1.updated_parameters(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        client1_client1_self[src_runtime]->_lf_updated_parameters.num_destinations = 1;
    }
    // For reference counting, set num_destinations for port client1.client1.num_train_samples.
    // Iterate over range client1.client1.num_train_samples(0,1)->[client1.client1.num_train_samples(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        client1_client1_self[src_runtime]->_lf_num_train_samples.num_destinations = 1;
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range client1.client1.updated_parameters(0,1)->[client1.client1.updated_parameters(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of client1.client1 triggers 1 downstream reactions
            // through port client1.client1.updated_parameters.
            client1_client1_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of client1.client1, allocate an
            // array of trigger pointers for downstream reactions through port client1.client1.updated_parameters
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &client1_client1_self[src_runtime]->base.allocations); 
            client1_client1_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range client1.client1.num_train_samples(0,1)->[client1.client1.num_train_samples(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of client1.client1 triggers 1 downstream reactions
            // through port client1.client1.num_train_samples.
            client1_client1_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of client1.client1, allocate an
            // array of trigger pointers for downstream reactions through port client1.client1.num_train_samples
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &client1_client1_self[src_runtime]->base.allocations); 
            client1_client1_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges client1.client1.updated_parameters(0,1)->[client1.client1.updated_parameters(0,1)] and client1.client1.updated_parameters(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range client1.client1.updated_parameters(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Port client1.client1.updated_parameters has reactions in its parent's parent.
                // Point to the trigger struct for those reactions.
                client1_client1_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &client1_main_self[dst_runtime]->_lf_client1.updated_parameters_trigger;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 1;
        // Iterate over ranges client1.client1.num_train_samples(0,1)->[client1.client1.num_train_samples(0,1)] and client1.client1.num_train_samples(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range client1.client1.num_train_samples(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Port client1.client1.num_train_samples has reactions in its parent's parent.
                // Point to the trigger struct for those reactions.
                client1_client1_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &client1_main_self[dst_runtime]->_lf_client1.num_train_samples_trigger;
            }
        }
    }
    // **** End of non-nested deferred initialize for client1.client1
    // **** End of non-nested deferred initialize for client1
    // Connect inputs and outputs for reactor client1.
    // Connect inputs and outputs for reactor client1.client1.
    // Connect client1.client1.global_parameter(0,1)->[client1.client1.global_parameter(0,1)] to port client1.client1.global_parameter(0,1)
    // Iterate over ranges client1.client1.global_parameter(0,1)->[client1.client1.global_parameter(0,1)] and client1.client1.global_parameter(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range client1.client1.global_parameter(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            client1_client1_self[dst_runtime]->_lf_global_parameter = (clientreactor463863444_global_parameter_t*)&client1_main_self[src_runtime]->_lf_client1.global_parameter;
        }
    }
    // Connect client1.client1.updated_parameters(0,1)->[client1.client1.updated_parameters(0,1)] to port client1.client1.updated_parameters(0,1)
    // Iterate over ranges client1.client1.updated_parameters(0,1)->[client1.client1.updated_parameters(0,1)] and client1.client1.updated_parameters(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range client1.client1.updated_parameters(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            client1_main_self[dst_runtime]->_lf_client1.updated_parameters = (clientreactor463863444_updated_parameters_t*)&client1_client1_self[src_runtime]->_lf_updated_parameters;
        }
    }
    // Connect client1.client1.num_train_samples(0,1)->[client1.client1.num_train_samples(0,1)] to port client1.client1.num_train_samples(0,1)
    // Iterate over ranges client1.client1.num_train_samples(0,1)->[client1.client1.num_train_samples(0,1)] and client1.client1.num_train_samples(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range client1.client1.num_train_samples(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            client1_main_self[dst_runtime]->_lf_client1.num_train_samples = (clientreactor463863444_num_train_samples_t*)&client1_client1_self[src_runtime]->_lf_num_train_samples;
        }
    }
    {
    }
    // Add port client1.client1.global_parameter to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                _lf_is_present_fields[0 + count] = &client1_main_self[0]->_lf_client1.global_parameter.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                _lf_intended_tag_fields[0 + count] = &client1_main_self[0]->_lf_client1.global_parameter.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    {
        // Add action client1.outputControlReactionTrigger to array of is_present fields.
        _lf_is_present_fields[1] 
                = &client1_main_self[0]->_lf_outputControlReactionTrigger.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action client1.outputControlReactionTrigger to array of intended_tag fields.
        _lf_intended_tag_fields[1] 
                = &client1_main_self[0]->_lf_outputControlReactionTrigger.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action client1.networkMessage_3 to array of is_present fields.
        _lf_is_present_fields[2] 
                = &client1_main_self[0]->_lf_networkMessage_3.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action client1.networkMessage_3 to array of intended_tag fields.
        _lf_intended_tag_fields[2] 
                = &client1_main_self[0]->_lf_networkMessage_3.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port client1.client1.updated_parameters to array of is_present fields.
            _lf_is_present_fields[3 + count] = &client1_client1_self[0]->_lf_updated_parameters.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port client1.client1.updated_parameters to array of intended_tag fields.
            _lf_intended_tag_fields[3 + count] = &client1_client1_self[0]->_lf_updated_parameters.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
            // Add port client1.client1.num_train_samples to array of is_present fields.
            _lf_is_present_fields[3 + count] = &client1_client1_self[0]->_lf_num_train_samples.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port client1.client1.num_train_samples to array of intended_tag fields.
            _lf_intended_tag_fields[3 + count] = &client1_client1_self[0]->_lf_num_train_samples.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    // Set reaction priorities for ReactorInstance client1
    {
        client1_main_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 2 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        client1_main_self[0]->_lf__reaction_0.index = 0xffffffffffff0002LL;
        client1_main_self[0]->_lf__reaction_1.chain_id = 1;
        // index is the OR of level 2 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        client1_main_self[0]->_lf__reaction_1.index = 0xffffffffffff0002LL;
        client1_main_self[0]->_lf__reaction_2.chain_id = 1;
        // index is the OR of level 2 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        client1_main_self[0]->_lf__reaction_2.index = 0xffffffffffff0002LL;
        client1_main_self[0]->_lf__reaction_3.chain_id = 1;
        // index is the OR of level 2 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        client1_main_self[0]->_lf__reaction_3.index = 0xffffffffffff0002LL;
        client1_main_self[0]->_lf__reaction_4.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        client1_main_self[0]->_lf__reaction_4.index = 0xffffffffffff0000LL;
        // Set reaction priorities for ReactorInstance client1.client1
        {
            client1_client1_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            client1_client1_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            client1_client1_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            client1_client1_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
        }
    }
    // Initialize the scheduler
    size_t num_reactions_per_level[3] = 
        {2, 1, 4};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 3};
    lf_sched_init(
        (size_t)_lf_number_of_workers,
        &sched_params
    );
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble();
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void _lf_trigger_startup_reactions() {
    for (int i = 0; i < _lf_startup_reactions_size; i++) {
        if (_lf_startup_reactions[i] != NULL) {
            _lf_trigger_reaction(_lf_startup_reactions[i], -1);
        }
    }
}
void _lf_initialize_timers() {
}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED
}
bool _lf_trigger_shutdown_reactions() {
    return false;
}
#ifndef FEDERATED
void terminate_execution() {}
#endif
